version: "3"
virtualmachines:
- name: web1
  image: centos-7-v20220303
  shell: /bin/bash
  machine_type: n1-standard-1
- name: puppet
  image: centos-7-v20220303
  shell: /bin/bash
  machine_type: n1-standard-4
- name: web2
  image: centos-7-v20220303
  shell: /bin/bash
  machine_type: n1-standard-1
