version: "3"
containers:
- name: guac
  image: gcr.io/instruqt/guacamole
  shell: /bin/bash
  ports:
  - 8080
  memory: 2048
virtualmachines:
- name: puppet
  image: kmo-instruqt/puppet-pe301-lab-1-0
  shell: /bin/bash
  machine_type: n1-highcpu-16
- name: winagent
  image: kmo-instruqt/winagent-pe301-lab-1-0
  machine_type: n1-highcpu-4
- name: nixagent2
  image: kmo-instruqt/nixagent2-pe301-lab-1-0
  shell: /bin/bash
  machine_type: n1-standard-4
- name: nixagent1
  image: kmo-instruqt/nixagent1-pe301-lab-1-0
  shell: /bin/bash
  machine_type: n1-standard-4
- name: gitea
  image: kmo-instruqt/gitea-pe301-lab-1-0
  shell: /bin/bash
  machine_type: n1-standard-4
