version: "3"
virtualmachines:
- name: nixagent
  image: kmo-instruqt/nixagent1-pe101-lab-2-1
  shell: /bin/bash
  machine_type: n1-standard-4
- name: puppet
  image: kmo-instruqt/puppet-pe101-lab-2-1
  shell: /bin/bash
  machine_type: n1-highcpu-8
