version: "3"
containers:
- name: guac
  image: gcr.io/instruqt/guacamole
  shell: /bin/bash
  ports:
  - 8080
  memory: 2048
- name: guac2
  image: gcr.io/instruqt/guacamole
  shell: /bin/bash
  ports:
  - 8080
  memory: 2048
virtualmachines:
- name: workstation
  image: kmo-instruqt/workstation-pe401-lab-1-0
  machine_type: n1-highcpu-8
- name: nixagent1
  image: kmo-instruqt/nixagent1-pe401-lab-1-0
  shell: /bin/bash
  machine_type: n1-standard-8
- name: nixagent2
  image: kmo-instruqt/nixagent2-pe401-lab-1-0
  shell: /bin/bash
  machine_type: n1-standard-8
- name: winagent
  image: kmo-instruqt/winagent-pe401-lab-1-0
  machine_type: n1-highcpu-8
- name: cd4pe-install-test
  image: kmo-instruqt/cd4pe-installed
  shell: /bin/bash
  machine_type: n1-highcpu-16
