version: "3"
virtualmachines:
- name: target1
  image: centos-7-v20220303
  shell: /bin/bash
  machine_type: n1-standard-1
- name: target2
  image: centos-7-v20220303
  shell: /bin/bash
  machine_type: n1-standard-1
- name: puppet
  image: centos-7-v20220303
  shell: /bin/bash
  machine_type: n1-standard-4
