version: "3"
containers:
- name: guac
  image: gcr.io/instruqt/guacamole
  shell: /bin/bash
  ports:
  - 8080
  memory: 2048
virtualmachines:
- name: nixagent3
  image: kmo-instruqt/nixagent2-pe501-lab-2-0
  shell: /bin/bash
  machine_type: n1-standard-8
- name: nixagent4
  image: kmo-instruqt/nixagent2-pe501-lab-2-0
  shell: /bin/bash
  machine_type: n1-standard-8
- name: nixagent1
  image: kmo-instruqt/nixagent1-pe501-lab-2-0
  shell: /bin/bash
  machine_type: n1-standard-8
- name: nixagent2
  image: kmo-instruqt/nixagent1-pe501-lab-2-0
  shell: /bin/bash
  machine_type: n1-standard-8
- name: puppet
  image: kmo-instruqt/puppet-pe501-lab-2-0
  shell: /bin/bash
  machine_type: n1-highcpu-16
- name: workstation
  image: kmo-instruqt/workstation-pe501-lab-2-0
  machine_type: n1-standard-8
- name: gitlab
  image: kmo-instruqt/gitlab-base
  shell: bash
  machine_type: n1-highcpu-32
- name: cd4pe-host
  image: kmo-instruqt/cd4pe-host
  shell: /bin/bash
  machine_type: n1-highcpu-16
